// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/addresses": {
            "get": {
                "description": "Derive EVM addresses from app's HD wallet",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "addresses"
                ],
                "summary": "Get EVM addresses",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Application ID",
                        "name": "appID",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Number of addresses to derive (default: 1, max: 100)",
                        "name": "count",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.SignedResponse-types_AddressesResponseV1"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/addresses/v2": {
            "get": {
                "description": "Derive EVM addresses from app's HD wallet, includes appId in response",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "addresses"
                ],
                "summary": "Get EVM addresses (V2)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Application ID",
                        "name": "appID",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Number of addresses to derive (default: 1, max: 100)",
                        "name": "count",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.SignedResponse-types_AddressesResponseV2"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/env": {
            "post": {
                "description": "Retrieve encrypted environment variables and mnemonic for authenticated app",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "environment"
                ],
                "summary": "Get environment variables",
                "parameters": [
                    {
                        "description": "Encrypted JWT + RSA public key data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.EnvRequestV1"
                        }
                    },
                    {
                        "type": "string",
                        "description": "App ID override (debug mode only)",
                        "name": "appID",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.SignedResponse-types_EnvResponseV1"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/env/v2": {
            "post": {
                "description": "Retrieve encrypted environment variables and mnemonic for authenticated app using attested RSA key",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "environment"
                ],
                "summary": "Get environment variables (V2)",
                "parameters": [
                    {
                        "description": "JWT with attested RSA public key",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.EnvRequestV2"
                        }
                    },
                    {
                        "type": "string",
                        "description": "App ID override (debug mode only)",
                        "name": "appID",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.SignedResponse-types_EnvResponseV2"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Get server health status",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "types.AddressesResponseV1": {
            "type": "object",
            "properties": {
                "evmAddresses": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.EVMAddressAndDerivationPath"
                    }
                },
                "solanaAddresses": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.SolanaAddressAndDerivationPath"
                    }
                }
            }
        },
        "types.AddressesResponseV2": {
            "type": "object",
            "properties": {
                "appId": {
                    "type": "string"
                },
                "evmAddresses": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.EVMAddressAndDerivationPath"
                    }
                },
                "solanaAddresses": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.SolanaAddressAndDerivationPath"
                    }
                }
            }
        },
        "types.EVMAddressAndDerivationPath": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string",
                    "example": "0x1234567890abcdef1234567890abcdef12345678"
                },
                "derivationPath": {
                    "type": "string"
                }
            }
        },
        "types.EnvRequestV1": {
            "type": "object",
            "properties": {
                "encryptedJwtWithRsaKey": {
                    "type": "string"
                }
            }
        },
        "types.EnvRequestV2": {
            "type": "object",
            "properties": {
                "jwtWithAttestedRsaKey": {
                    "type": "string"
                },
                "rsaKey": {
                    "type": "string"
                }
            }
        },
        "types.EnvResponseV1": {
            "type": "object",
            "properties": {
                "encryptedCombinedEnv": {
                    "type": "string"
                }
            }
        },
        "types.EnvResponseV2": {
            "type": "object",
            "properties": {
                "encryptedCombinedEnv": {
                    "type": "string"
                }
            }
        },
        "types.SignedResponse-types_AddressesResponseV1": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/types.AddressesResponseV1"
                },
                "signature": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "types.SignedResponse-types_AddressesResponseV2": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/types.AddressesResponseV2"
                },
                "signature": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "types.SignedResponse-types_EnvResponseV1": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/types.EnvResponseV1"
                },
                "signature": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "types.SignedResponse-types_EnvResponseV2": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/types.EnvResponseV2"
                },
                "signature": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "types.SolanaAddressAndDerivationPath": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "derivationPath": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Compute TEE KMS API",
	Description:      "KMS service for Compute TEE",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
