// Code generated by MockGen. DO NOT EDIT.
// Source: chainclient.go
//
// Generated by this command:
//
//	mockgen -source=chainclient.go -destination=mocks/mock_chainclient.go -package=mocks ChainClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	types "github.com/Layr-Labs/eigenx-kms/pkg/types"
	gomock "go.uber.org/mock/gomock"
)

// MockChainClient is a mock of ChainClient interface.
type MockChainClient struct {
	ctrl     *gomock.Controller
	recorder *MockChainClientMockRecorder
	isgomock struct{}
}

// MockChainClientMockRecorder is the mock recorder for MockChainClient.
type MockChainClientMockRecorder struct {
	mock *MockChainClient
}

// NewMockChainClient creates a new mock instance.
func NewMockChainClient(ctrl *gomock.Controller) *MockChainClient {
	mock := &MockChainClient{ctrl: ctrl}
	mock.recorder = &MockChainClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChainClient) EXPECT() *MockChainClientMockRecorder {
	return m.recorder
}

// GetLatestRelease mocks base method.
func (m *MockChainClient) GetLatestRelease(ctx context.Context, appID string) ([32]byte, types.Env, []byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestRelease", ctx, appID)
	ret0, _ := ret[0].([32]byte)
	ret1, _ := ret[1].(types.Env)
	ret2, _ := ret[2].([]byte)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetLatestRelease indicates an expected call of GetLatestRelease.
func (mr *MockChainClientMockRecorder) GetLatestRelease(ctx, appID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestRelease", reflect.TypeOf((*MockChainClient)(nil).GetLatestRelease), ctx, appID)
}
