// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Layr-Labs/eigenx-kms/pkg/types (interfaces: AppController,AppUpgradedIterator)
//
// Generated by this command:
//
//	mockgen -destination=../chainclient/mocks/mock_app_interfaces.go -package=mocks . AppController,AppUpgradedIterator
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	AppController "github.com/Layr-Labs/eigenx-contracts/pkg/bindings/v1/AppController"
	types "github.com/Layr-Labs/eigenx-kms/pkg/types"
	bind "github.com/ethereum/go-ethereum/accounts/abi/bind"
	common "github.com/ethereum/go-ethereum/common"
	gomock "go.uber.org/mock/gomock"
)

// MockAppController is a mock of AppController interface.
type MockAppController struct {
	ctrl     *gomock.Controller
	recorder *MockAppControllerMockRecorder
	isgomock struct{}
}

// MockAppControllerMockRecorder is the mock recorder for MockAppController.
type MockAppControllerMockRecorder struct {
	mock *MockAppController
}

// NewMockAppController creates a new mock instance.
func NewMockAppController(ctrl *gomock.Controller) *MockAppController {
	mock := &MockAppController{ctrl: ctrl}
	mock.recorder = &MockAppControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAppController) EXPECT() *MockAppControllerMockRecorder {
	return m.recorder
}

// ComputeAVSRegistrar mocks base method.
func (m *MockAppController) ComputeAVSRegistrar(opts *bind.CallOpts) (common.Address, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ComputeAVSRegistrar", opts)
	ret0, _ := ret[0].(common.Address)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ComputeAVSRegistrar indicates an expected call of ComputeAVSRegistrar.
func (mr *MockAppControllerMockRecorder) ComputeAVSRegistrar(opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ComputeAVSRegistrar", reflect.TypeOf((*MockAppController)(nil).ComputeAVSRegistrar), opts)
}

// FilterAppUpgraded mocks base method.
func (m *MockAppController) FilterAppUpgraded(opts *bind.FilterOpts, apps []common.Address) (types.AppUpgradedIterator, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterAppUpgraded", opts, apps)
	ret0, _ := ret[0].(types.AppUpgradedIterator)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilterAppUpgraded indicates an expected call of FilterAppUpgraded.
func (mr *MockAppControllerMockRecorder) FilterAppUpgraded(opts, apps any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterAppUpgraded", reflect.TypeOf((*MockAppController)(nil).FilterAppUpgraded), opts, apps)
}

// GetAppCreator mocks base method.
func (m *MockAppController) GetAppCreator(opts *bind.CallOpts, app common.Address) (common.Address, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAppCreator", opts, app)
	ret0, _ := ret[0].(common.Address)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAppCreator indicates an expected call of GetAppCreator.
func (mr *MockAppControllerMockRecorder) GetAppCreator(opts, app any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppCreator", reflect.TypeOf((*MockAppController)(nil).GetAppCreator), opts, app)
}

// GetAppLatestReleaseBlockNumber mocks base method.
func (m *MockAppController) GetAppLatestReleaseBlockNumber(opts *bind.CallOpts, app common.Address) (uint32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAppLatestReleaseBlockNumber", opts, app)
	ret0, _ := ret[0].(uint32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAppLatestReleaseBlockNumber indicates an expected call of GetAppLatestReleaseBlockNumber.
func (mr *MockAppControllerMockRecorder) GetAppLatestReleaseBlockNumber(opts, app any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppLatestReleaseBlockNumber", reflect.TypeOf((*MockAppController)(nil).GetAppLatestReleaseBlockNumber), opts, app)
}

// GetAppOperatorSetId mocks base method.
func (m *MockAppController) GetAppOperatorSetId(opts *bind.CallOpts, app common.Address) (uint32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAppOperatorSetId", opts, app)
	ret0, _ := ret[0].(uint32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAppOperatorSetId indicates an expected call of GetAppOperatorSetId.
func (mr *MockAppControllerMockRecorder) GetAppOperatorSetId(opts, app any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppOperatorSetId", reflect.TypeOf((*MockAppController)(nil).GetAppOperatorSetId), opts, app)
}

// GetAppStatus mocks base method.
func (m *MockAppController) GetAppStatus(opts *bind.CallOpts, app common.Address) (uint8, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAppStatus", opts, app)
	ret0, _ := ret[0].(uint8)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAppStatus indicates an expected call of GetAppStatus.
func (mr *MockAppControllerMockRecorder) GetAppStatus(opts, app any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppStatus", reflect.TypeOf((*MockAppController)(nil).GetAppStatus), opts, app)
}

// ReleaseManager mocks base method.
func (m *MockAppController) ReleaseManager(opts *bind.CallOpts) (common.Address, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseManager", opts)
	ret0, _ := ret[0].(common.Address)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReleaseManager indicates an expected call of ReleaseManager.
func (mr *MockAppControllerMockRecorder) ReleaseManager(opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseManager", reflect.TypeOf((*MockAppController)(nil).ReleaseManager), opts)
}

// MockAppUpgradedIterator is a mock of AppUpgradedIterator interface.
type MockAppUpgradedIterator struct {
	ctrl     *gomock.Controller
	recorder *MockAppUpgradedIteratorMockRecorder
	isgomock struct{}
}

// MockAppUpgradedIteratorMockRecorder is the mock recorder for MockAppUpgradedIterator.
type MockAppUpgradedIteratorMockRecorder struct {
	mock *MockAppUpgradedIterator
}

// NewMockAppUpgradedIterator creates a new mock instance.
func NewMockAppUpgradedIterator(ctrl *gomock.Controller) *MockAppUpgradedIterator {
	mock := &MockAppUpgradedIterator{ctrl: ctrl}
	mock.recorder = &MockAppUpgradedIteratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAppUpgradedIterator) EXPECT() *MockAppUpgradedIteratorMockRecorder {
	return m.recorder
}

// Event mocks base method.
func (m *MockAppUpgradedIterator) Event() *AppController.AppControllerAppUpgraded {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Event")
	ret0, _ := ret[0].(*AppController.AppControllerAppUpgraded)
	return ret0
}

// Event indicates an expected call of Event.
func (mr *MockAppUpgradedIteratorMockRecorder) Event() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Event", reflect.TypeOf((*MockAppUpgradedIterator)(nil).Event))
}

// Next mocks base method.
func (m *MockAppUpgradedIterator) Next() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Next")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Next indicates an expected call of Next.
func (mr *MockAppUpgradedIteratorMockRecorder) Next() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Next", reflect.TypeOf((*MockAppUpgradedIterator)(nil).Next))
}
