// Code generated by MockGen. DO NOT EDIT.
// Source: policy.go
//
// Generated by this command:
//
//	mockgen -source=policy.go -destination=mocks/mock_policy.go -package=mocks PolicyCheckerInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	ImageAllowlist "github.com/Layr-Labs/eigenx-contracts/pkg/bindings/v1/ImageAllowlist"
	teeverify "github.com/Layr-Labs/go-tpm-tools/teeverify"
	gomock "go.uber.org/mock/gomock"
)

// MockImageAllowlistChecker is a mock of ImageAllowlistChecker interface.
type MockImageAllowlistChecker struct {
	ctrl     *gomock.Controller
	recorder *MockImageAllowlistCheckerMockRecorder
	isgomock struct{}
}

// MockImageAllowlistCheckerMockRecorder is the mock recorder for MockImageAllowlistChecker.
type MockImageAllowlistCheckerMockRecorder struct {
	mock *MockImageAllowlistChecker
}

// NewMockImageAllowlistChecker creates a new mock instance.
func NewMockImageAllowlistChecker(ctrl *gomock.Controller) *MockImageAllowlistChecker {
	mock := &MockImageAllowlistChecker{ctrl: ctrl}
	mock.recorder = &MockImageAllowlistCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImageAllowlistChecker) EXPECT() *MockImageAllowlistCheckerMockRecorder {
	return m.recorder
}

// IsImageAllowed mocks base method.
func (m *MockImageAllowlistChecker) IsImageAllowed(ctx context.Context, cvm uint8, pcrs []ImageAllowlist.IImageAllowlistPCR) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsImageAllowed", ctx, cvm, pcrs)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsImageAllowed indicates an expected call of IsImageAllowed.
func (mr *MockImageAllowlistCheckerMockRecorder) IsImageAllowed(ctx, cvm, pcrs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsImageAllowed", reflect.TypeOf((*MockImageAllowlistChecker)(nil).IsImageAllowed), ctx, cvm, pcrs)
}

// IsTCBValid mocks base method.
func (m *MockImageAllowlistChecker) IsTCBValid(ctx context.Context, cvm uint8, tcb uint64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsTCBValid", ctx, cvm, tcb)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsTCBValid indicates an expected call of IsTCBValid.
func (mr *MockImageAllowlistCheckerMockRecorder) IsTCBValid(ctx, cvm, tcb any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsTCBValid", reflect.TypeOf((*MockImageAllowlistChecker)(nil).IsTCBValid), ctx, cvm, tcb)
}

// MockPolicyCheckerInterface is a mock of PolicyCheckerInterface interface.
type MockPolicyCheckerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPolicyCheckerInterfaceMockRecorder
	isgomock struct{}
}

// MockPolicyCheckerInterfaceMockRecorder is the mock recorder for MockPolicyCheckerInterface.
type MockPolicyCheckerInterfaceMockRecorder struct {
	mock *MockPolicyCheckerInterface
}

// NewMockPolicyCheckerInterface creates a new mock instance.
func NewMockPolicyCheckerInterface(ctrl *gomock.Controller) *MockPolicyCheckerInterface {
	mock := &MockPolicyCheckerInterface{ctrl: ctrl}
	mock.recorder = &MockPolicyCheckerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPolicyCheckerInterface) EXPECT() *MockPolicyCheckerInterfaceMockRecorder {
	return m.recorder
}

// CheckPolicies mocks base method.
func (m *MockPolicyCheckerInterface) CheckPolicies(ctx context.Context, claims *teeverify.Claims, platform teeverify.Platform) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckPolicies", ctx, claims, platform)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckPolicies indicates an expected call of CheckPolicies.
func (mr *MockPolicyCheckerInterfaceMockRecorder) CheckPolicies(ctx, claims, platform any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckPolicies", reflect.TypeOf((*MockPolicyCheckerInterface)(nil).CheckPolicies), ctx, claims, platform)
}
