// Code generated by MockGen. DO NOT EDIT.
// Source: attestation.go
//
// Generated by this command:
//
//	mockgen -source=attestation.go -destination=mocks/mock_attestation.go -package=mocks AttestationVerifierInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	attestation "github.com/Layr-Labs/eigenx-kms/pkg/attestation"
	gomock "go.uber.org/mock/gomock"
)

// MockAttestationVerifierInterface is a mock of AttestationVerifierInterface interface.
type MockAttestationVerifierInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAttestationVerifierInterfaceMockRecorder
	isgomock struct{}
}

// MockAttestationVerifierInterfaceMockRecorder is the mock recorder for MockAttestationVerifierInterface.
type MockAttestationVerifierInterfaceMockRecorder struct {
	mock *MockAttestationVerifierInterface
}

// NewMockAttestationVerifierInterface creates a new mock instance.
func NewMockAttestationVerifierInterface(ctrl *gomock.Controller) *MockAttestationVerifierInterface {
	mock := &MockAttestationVerifierInterface{ctrl: ctrl}
	mock.recorder = &MockAttestationVerifierInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAttestationVerifierInterface) EXPECT() *MockAttestationVerifierInterfaceMockRecorder {
	return m.recorder
}

// VerifyAttestation mocks base method.
func (m *MockAttestationVerifierInterface) VerifyAttestation(ctx context.Context, tokenString string) (*attestation.AttestationClaims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyAttestation", ctx, tokenString)
	ret0, _ := ret[0].(*attestation.AttestationClaims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyAttestation indicates an expected call of VerifyAttestation.
func (mr *MockAttestationVerifierInterfaceMockRecorder) VerifyAttestation(ctx, tokenString any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyAttestation", reflect.TypeOf((*MockAttestationVerifierInterface)(nil).VerifyAttestation), ctx, tokenString)
}
