// Code generated by MockGen. DO NOT EDIT.
// Source: bound_attestation_evidence.go
//
// Generated by this command:
//
//	mockgen -source=bound_attestation_evidence_verifier.go -destination=mocks/mock_bound_attestation_evidence_verifier.go -package=mocks BoundAttestationEvidenceVerifier
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	attestation "github.com/Layr-Labs/eigenx-kms/pkg/attestation"
	gomock "go.uber.org/mock/gomock"
)

// MockBoundAttestationEvidenceVerifier is a mock of BoundAttestationEvidenceVerifier interface.
type MockBoundAttestationEvidenceVerifier struct {
	ctrl     *gomock.Controller
	recorder *MockBoundAttestationEvidenceVerifierMockRecorder
	isgomock struct{}
}

// MockBoundAttestationEvidenceVerifierMockRecorder is the mock recorder for MockBoundAttestationEvidenceVerifier.
type MockBoundAttestationEvidenceVerifierMockRecorder struct {
	mock *MockBoundAttestationEvidenceVerifier
}

// NewMockBoundAttestationEvidenceVerifier creates a new mock instance.
func NewMockBoundAttestationEvidenceVerifier(ctrl *gomock.Controller) *MockBoundAttestationEvidenceVerifier {
	mock := &MockBoundAttestationEvidenceVerifier{ctrl: ctrl}
	mock.recorder = &MockBoundAttestationEvidenceVerifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBoundAttestationEvidenceVerifier) EXPECT() *MockBoundAttestationEvidenceVerifierMockRecorder {
	return m.recorder
}

// Verify mocks base method.
func (m *MockBoundAttestationEvidenceVerifier) Verify(ctx context.Context, attestationBytes, challenge []byte) (*attestation.VerifiedAttestation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Verify", ctx, attestationBytes, challenge)
	ret0, _ := ret[0].(*attestation.VerifiedAttestation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Verify indicates an expected call of Verify.
func (mr *MockBoundAttestationEvidenceVerifierMockRecorder) Verify(ctx, attestationBytes, challenge any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Verify", reflect.TypeOf((*MockBoundAttestationEvidenceVerifier)(nil).Verify), ctx, attestationBytes, challenge)
}
