// Code generated by MockGen. DO NOT EDIT.
// Source: kms.go
//
// Generated by this command:
//
//	mockgen -source=kms.go -destination=mocks/mock_kms.go -package=mocks KMSClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	jwa "github.com/lestrrat-go/jwx/v3/jwa"
	jwe "github.com/lestrrat-go/jwx/v3/jwe"
	gomock "go.uber.org/mock/gomock"
)

// MockKMSClient is a mock of KMSClient interface.
type MockKMSClient struct {
	ctrl     *gomock.Controller
	recorder *MockKMSClientMockRecorder
	isgomock struct{}
}

// MockKMSClientMockRecorder is the mock recorder for MockKMSClient.
type MockKMSClientMockRecorder struct {
	mock *MockKMSClient
}

// NewMockKMSClient creates a new mock instance.
func NewMockKMSClient(ctrl *gomock.Controller) *MockKMSClient {
	mock := &MockKMSClient{ctrl: ctrl}
	mock.recorder = &MockKMSClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKMSClient) EXPECT() *MockKMSClientMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockKMSClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockKMSClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockKMSClient)(nil).Close))
}

// DecryptBytes mocks base method.
func (m *MockKMSClient) DecryptBytes(ctx context.Context, encryptedData []byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecryptBytes", ctx, encryptedData)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecryptBytes indicates an expected call of DecryptBytes.
func (mr *MockKMSClientMockRecorder) DecryptBytes(ctx, encryptedData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecryptBytes", reflect.TypeOf((*MockKMSClient)(nil).DecryptBytes), ctx, encryptedData)
}

// DecryptKey mocks base method.
func (m *MockKMSClient) DecryptKey(alg jwa.KeyEncryptionAlgorithm, encryptedKey []byte, arg2 jwe.Recipient, arg3 *jwe.Message) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecryptKey", alg, encryptedKey, arg2, arg3)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecryptKey indicates an expected call of DecryptKey.
func (mr *MockKMSClientMockRecorder) DecryptKey(alg, encryptedKey, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecryptKey", reflect.TypeOf((*MockKMSClient)(nil).DecryptKey), alg, encryptedKey, arg2, arg3)
}

// DeriveMnemonic mocks base method.
func (m *MockKMSClient) DeriveMnemonic(ctx context.Context, appID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeriveMnemonic", ctx, appID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeriveMnemonic indicates an expected call of DeriveMnemonic.
func (mr *MockKMSClientMockRecorder) DeriveMnemonic(ctx, appID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeriveMnemonic", reflect.TypeOf((*MockKMSClient)(nil).DeriveMnemonic), ctx, appID)
}

// SignMessage mocks base method.
func (m *MockKMSClient) SignMessage(ctx context.Context, message string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignMessage", ctx, message)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SignMessage indicates an expected call of SignMessage.
func (mr *MockKMSClientMockRecorder) SignMessage(ctx, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignMessage", reflect.TypeOf((*MockKMSClient)(nil).SignMessage), ctx, message)
}
